### ISSUE TITLE
Error "ReferenceError: Blob is not defined" when trying to add a canned response for a user

### ISSUE THREAD

**Issue by joolswills** [julianlam/nodebb-plugin-canned-responses#41]
* NodeBB v2.6.1
* MongoDB 4.4.18
* nodebb-plugin-canned-responses v2.4.8

I go to "Edit Profile" for my user, then "Canned Responses".

Then go to "Add New Response". Filling out the form and submitting it throws the following error:

Error log: (I only stripped the absolute location of the installation)
``` 
2022-11-28T21:46:23.581Z [4569/18205] - ESC[31merrorESC[39m: POST /forum/user/buzz/canned-responses
ReferenceError: Blob is not defined
    at Object.utils.generateUUID (nodebb/public/src/utils.js:77:43)
    at Object.responses.add (nodebb/node_modules/nodebb-plugin-canned-responses/lib/responses.js:87:27)
    at Controllers.add (nodebb/node_modules/nodebb-plugin-canned-responses/lib/controllers.js:79:12)
    at Layer.handle [as handle_request] (nodebb/node_modules/express/lib/router/layer.js:95:5)
    at next (nodebb/node_modules/express/lib/router/route.js:144:13)
    at middleware.restrictToProfileOwner (nodebb/node_modules/nodebb-plugin-canned-responses/lib/middleware.js:8:3)
    at Layer.handle [as handle_request] (nodebb/node_modules/express/lib/router/layer.js:95:5)
    at next (nodebb/node_modules/express/lib/router/route.js:144:13)
    at expose (nodebb/src/middleware/index.js:154:2)
    at runMicrotasks (<anonymous>)
```

**Comment by julianlam** [comment]
Hi, sorry for the delay, did you resolve the issue?

Are you using the Quill composer?

**Comment by joolswills** [comment]
Sorry I missed your reply before.

Was just testing as moved to nodeBB v3.2.2 and wanted to see if it was still an issue - the same error is occurring. 

We are using nodebb-plugin-composer-default.

**Comment by joolswills** [comment]
Just to note - Updated nodebb to 3.5.1 and canned responses to v2.6.0 and getting the same issue when trying to add a canned response.

```
error: POST /forum/user/buzz/canned-responses
ReferenceError: Blob is not defined
    at Object.utils.generateUUID (nodebb/public/src/utils.js:82:43)
    at Object.responses.add (nodebb/node_modules/nodebb-plugin-canned-responses/lib/responses.js:87:27)
    at Controllers.add (nodebb/node_modules/nodebb-plugin-canned-responses/lib/controllers.js:90:12)
    at Layer.handle [as handle_request] (nodebb/node_modules/express/lib/router/layer.js:95:5)
    at next (nodebb/node_modules/express/lib/router/route.js:144:13)
    at middleware.restrictToProfileOwner (nodebb/node_modules/nodebb-plugin-canned-responses/lib/middleware.js:8:3)
    at Layer.handle [as handle_request] (nodebb/node_modules/express/lib/router/layer.js:95:5)
    at next (nodebb/node_modules/express/lib/router/route.js:144:13)
    at expose (nodebb/src/middleware/index.js:182:2)
    at runMicrotasks (<anonymous>)

```

**Comment by joolswills** [comment]
Since updating Node to v20 and NodeBB to v3.6.3 this is now working. Thanks.
