### ISSUE TITLE
Modal broken 1.1.2

### ISSUE THREAD

**Issue by exomarty** [julianlam/nodebb-plugin-canned-responses#9]
It doesnt seems to open modal on the composer
Nodebb 1.1.2

**Comment by exomarty** [comment]
I mean on 1.2.1

**Comment by julianlam** [comment]
I am unable to reproduce, modal opens fine on `master` and `v1.2.1` of NodeBB.

**Comment by exomarty** [comment]
i get this error

- error: /canned-responses
 TypeError: callback is not a function
    at getSortedSetUnion (/var/foroexodo/nodebb/src/database/mongo/sorted.js:511:11)
    at Object.module.getSortedSetUnion (/var/foroexodo/nodebb/src/database/mongo/sorted.js:501:3)
    at Object.responses.list (/var/foroexodo/nodebb/node_modules/nodebb-plugin-canned-responses/lib/response                                                s.js:18:12)
    at Controllers.getAll (/var/foroexodo/nodebb/node_modules/nodebb-plugin-canned-responses/lib/controllers                                                .js:55:12)
    at Layer.handle [as handle_request] (/var/foroexodo/nodebb/node_modules/express/lib/router/layer.js:95:5                                                )
    at next (/var/foroexodo/nodebb/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/var/foroexodo/nodebb/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/var/foroexodo/nodebb/node_modules/express/lib/router/layer.js:95:5                                                )
    at /var/foroexodo/nodebb/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:330:12)
    at next (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:176:3)
    at router (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:46:12)
    at Layer.handle [as handle_request] (/var/foroexodo/nodebb/node_modules/express/lib/router/layer.js:95:5                                                )
    at trim_prefix (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:312:13)
    at /var/foroexodo/nodebb/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:330:12)
    at next (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:271:10)
    at middleware.maintenanceMode (/var/foroexodo/nodebb/src/middleware/maintenance.js:11:11)
    at Layer.handle [as handle_request] (/var/foroexodo/nodebb/node_modules/express/lib/router/layer.js:95:5                                                )
    at trim_prefix (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:312:13)
    at /var/foroexodo/nodebb/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:330:12)
    at next (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:271:10)
    at Logger.expressLogger (/var/foroexodo/nodebb/src/logger.js:140:11)
    at Layer.handle [as handle_request] (/var/foroexodo/nodebb/node_modules/express/lib/router/layer.js:95:5                                                )
    at trim_prefix (/var/foroexodo/nodebb/node_modules/express/lib/router/index.js:312:13)
    at /var/foroexodo/nodebb/node_modules/express/lib/router/index.js:280:7

**Comment by exomarty** [comment]
this is the error on the browser
![captura de pantalla 2016-10-29 a las 20 51 22](https://cloud.githubusercontent.com/assets/10746278/19832026/840382d8-9e19-11e6-9b5f-dd29955cd15b.png)

**Comment by julianlam** [comment]
Plugin version?

**Comment by exomarty** [comment]
Last one. Just reinstalles it again from package manager

**Comment by julianlam** [comment]
Need version # of canned responses plugin to ensure it actually affects latest... as you know, no repro means no fix, unfortunately.

**Comment by exomarty** [comment]
1.1.3 is the one i have installed

**Comment by exomarty** [comment]
just installed clean nodebb branch 1.x.x -> 1.2.1 up to date
theme persona and no other plugins

Canned responses Installed 1.1.3 | Latest 1.1.3
Node js 4.0
redis db



I get this error while clicking on canned composer button


10/11 14:24 [25152] - info: NodeBB is now listening on: 0.0.0.0:4567
10/11 14:25 [25152] - error: /canned-responses
 TypeError: Cannot read property 'length' of undefined
    at sortedSetUnion (/volume1/web/nodebb/src/database/redis/sorted.js:272:46)
    at Object.module.getSortedSetUnion (/volume1/web/nodebb/src/database/redis/sorted.js:254:3)
    at Object.responses.list (/volume1/web/nodebb/node_modules/nodebb-plugin-canned-responses/lib/responses.js:18:12)
    at Controllers.getAll (/volume1/web/nodebb/node_modules/nodebb-plugin-canned-responses/lib/controllers.js:55:12)
    at Layer.handle [as handle_request] (/volume1/web/nodebb/node_modules/express/lib/router/layer.js:95:5)
    at next (/volume1/web/nodebb/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/volume1/web/nodebb/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/volume1/web/nodebb/node_modules/express/lib/router/layer.js:95:5)
    at /volume1/web/nodebb/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/volume1/web/nodebb/node_modules/express/lib/router/index.js:330:12)
    at next (/volume1/web/nodebb/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/volume1/web/nodebb/node_modules/express/lib/router/index.js:176:3)
    at router (/volume1/web/nodebb/node_modules/express/lib/router/index.js:46:12)
    at Layer.handle [as handle_request] (/volume1/web/nodebb/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/volume1/web/nodebb/node_modules/express/lib/router/index.js:312:13)
    at /volume1/web/nodebb/node_modules/express/lib/router/index.js:280:7

**Comment by julianlam** [comment]
Use latest version on nbbpm. Should be updated now.
